name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: npm install
      
      - name: Install angular-cli-ghpages
        run: npm install -g angular-cli-ghpages
      
      - name: Build and Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ng build --configuration production --base-href=/underwrite-pro/
          
          # Add .nojekyll file (prevents GitHub Pages from ignoring files that begin with an underscore)
          touch dist/underwrite-pro/.nojekyll
          
          # Fix the CSP issue by modifying the index.html
          sed -i 's/<head>/<head>\n  <meta http-equiv="Content-Security-Policy" content="default-src '\''self'\''; script-src '\''self'\'' '\''unsafe-eval'\'' '\''unsafe-inline'\''; style-src '\''self'\'' '\''unsafe-inline'\''; img-src '\''self'\'' data:;">/' dist/underwrite-pro/index.html
          
          # Create a 404.html file that's the same as index.html for proper SPA routing
          cp dist/underwrite-pro/index.html dist/underwrite-pro/404.html
          
          # Deploy using angular-cli-ghpages
          npx -y angular-cli-ghpages --dir=dist/underwrite-pro --name="GitHub Actions" --email="actions@github.com" --no-silent 