name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Show workspace contents before build
        run: |
          echo "Current workspace contents:"
          ls -la
          echo "Gitignore contents:"
          cat .gitignore
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Display Angular CLI version
        run: npx ng version
      
      - name: Build with --verbose flag
        run: npm run build -- --configuration=production --base-href="/underwrite-pro/" --verbose
      
      - name: Debug build output
        run: |
          echo "Checking dist directory:"
          ls -la dist || echo "No dist directory found"
          echo "Checking dist/underwrite-pro directory:"
          ls -la dist/underwrite-pro || echo "No dist/underwrite-pro directory found"
          echo "Finding JavaScript files:"
          find dist -name "*.js" | sort || echo "No JavaScript files found"
      
      - name: Create Angular 404.html for routing
        run: |
          # Create an Angular-compatible 404.html for client-side routing
          cp dist/underwrite-pro/index.html dist/underwrite-pro/404.html
      
      - name: Show final build contents
        run: |
          echo "Final build contents:"
          ls -la dist/underwrite-pro/
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './dist/underwrite-pro'
      
      - name: Upload backup of build files (for debug)
        uses: actions/upload-artifact@v3
        with:
          name: angular-build-files
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 